name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  tests:
    name: Unit tests (pytest)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-cov

      - name: Run tests (always produce reports)
        run: |
          set -o pipefail
          pytest -q --maxfail=1 --disable-warnings \
            --junitxml=results.xml \
            --cov=. --cov-report=xml || true
          test -f results.xml || echo '<testsuite tests="0" errors="0" failures="0" skipped="0"></testsuite>' > results.xml
          test -f coverage.xml || echo '<coverage line-rate="0.0"></coverage>' > coverage.xml

      # Only one matrix leg (3.11) updates README on main to avoid races
      - name: Update README badges (tests + coverage)
        if: github.ref == 'refs/heads/main' && matrix.python-version == '3.11'
        permissions:
          contents: write
        run: |
          python - << 'PY'
          import pathlib, re, sys
          import xml.etree.ElementTree as ET
          from urllib.parse import quote

          readme = pathlib.Path("README.md")
          if not readme.exists():
              print("README.md not found; skipping badge update.")
              sys.exit(0)

          # --- Parse tests from results.xml (JUnit) ---
          try:
              root = ET.parse("results.xml").getroot()
          except Exception as e:
              print("Failed to parse results.xml:", e)
              sys.exit(0)

          def gi(node, attr):
              v = node.attrib.get(attr, "0")
              try: return int(float(v))
              except: return 0

          def sum_suite(node):
              return {
                  "tests": gi(node, "tests"),
                  "errors": gi(node, "errors"),
                  "failures": gi(node, "failures"),
                  "skipped": gi(node, "skipped") or gi(node, "disabled"),
              }

          if root.tag == "testsuite":
              t = sum_suite(root)
          else:
              t = {"tests":0,"errors":0,"failures":0,"skipped":0}
              for ts in root.findall(".//testsuite"):
                  tt = sum_suite(ts)
                  for k in t: t[k] += tt[k]

          total  = t["tests"]
          failed = t["failures"] + t["errors"]
          passed = max(0, total - failed - t["skipped"])

          if total == 0:
              test_color = "lightgrey"
          elif failed == 0 and passed == total:
              test_color = "brightgreen"
          elif failed == 0:
              test_color = "yellow"
          else:
              test_color = "red"

          tests_badge = f"https://img.shields.io/badge/{quote('tests')}-{quote(f'{passed}/{total} passing')}/{test_color}"

          # --- Parse coverage from coverage.xml (Cobertura) ---
          try:
              cov_root = ET.parse("coverage.xml").getroot()
              line_rate = float(cov_root.attrib.get("line-rate", "0")) * 100.0
          except Exception as e:
              print("Failed to parse coverage.xml:", e)
              line_rate = 0.0

          pct = round(line_rate, 1)
          if pct >= 90: cov_color = "brightgreen"
          elif pct >= 75: cov_color = "yellowgreen"
          elif pct >= 50: cov_color = "orange"
          else: cov_color = "red" if total > 0 else "lightgrey"

          coverage_badge = f"https://img.shields.io/badge/{quote('coverage')}-{quote(str(pct)+'%')}-{cov_color}"

          # --- Replace blocks in README ---
          text0 = readme.read_text(encoding="utf-8")

          def replace_block(text, start, end, url, alt):
              pattern = rf"({re.escape(start)})(.*?)({re.escape(end)})"
              replacement = rf"\1\n![{alt}]({url})\n\3"
              new_text, n = re.subn(pattern, replacement, text, flags=re.S)
              return new_text, n

          text1, n1 = replace_block(text0, "<!-- TESTS_BADGE:START -->", "<!-- TESTS_BADGE:END -->", tests_badge, "Tests")
          text2, n2 = replace_block(text1, "<!-- COVERAGE_BADGE:START -->", "<!-- COVERAGE_BADGE:END -->", coverage_badge, "Coverage")

          if (n1 + n2) == 0:
              print("Badge markers not found in README.md; skipping.")
              sys.exit(0)

          if text2 != text0:
              readme.write_text(text2, encoding="utf-8")
              print("README badges updated.")
          else:
              print("README already up to date.")
          PY

      - name: Commit README update (if changed)
        if: github.ref == 'refs/heads/main' && matrix.python-version == '3.11'
        run: |
          if git diff --quiet README.md; then
            echo "No README changes."
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update tests & coverage badges [skip ci]"
          git push
